select*from applications
select*from candidate_certifications
select*from candidate_profiles
select*from candidate_skills
select*from candidates
select*from certifications
select*from companies
select*from company_locations
select*from hires
select*from interview_feedback
select*from interview_rounds
select*from interviews
select*from job_categories
select*from job_postings
select*from job_skills
select*from login_activity
select*from offers
select*from payments
select*from recruiters
select*from skills